### ISSUE TITLE
Memory Error in return_weighted_distance or fit method when size of samples are more than 25000

### ISSUE THREAD

**Issue by emnajaoua** [Csinclair0/feature_learning#1]
Hi,
I would like to thank you for your implementation. it's so clear and understandable. The problem is that I have a very large dataset (in the order of Millions of samples). when I take only 20000 instances, the return_weighted_distance and the fit method works well but that's not enough for me. Do you have any solutions or suggestions how can I run the fuzzy c-means model without having this memory error.

`MemoryError                               Traceback (most recent call last)
<ipython-input-60-6f7f9247ff0d> in <module>
      3 threshold= .00001
      4 #weights =  [1,1,0.5,0.5, 1,1,0.2,1, 1]
----> 5 w = feature_learning.return_weighted_distance(t, threshold = threshold, max_iter = max_iter, n = 15)

~\Documents\ProjectY\feature_learning.py in return_weighted_distance(X, mincols, sample_size, threshold, n, max_iter)
    241     X_S = X#X[sample]
    242     d = pairwise_distances(X_S, X_S, metric = 'euclidean')
--> 243     b = calc_beta(X_S, d)
    244     w = return_weights(X_S, b, d, mincols, threshold, n, max_iter)
    245     w = w.reshape(1,-1)

~\Documents\ProjectY\feature_learning.py in calc_beta(X, d)
     69     for b in np.linspace(0,1,10000):
     70         p = 1/(1+b*d)
---> 71         p = np.triu(p, 1)
     72         if (2 / (n*(n-1))) *np.sum(p)< .5:
     73             return b

~\AppData\Local\Continuum\anaconda3\lib\site-packages\numpy\lib\twodim_base.py in triu(m, k)
    465     mask = tri(*m.shape[-2:], k=k-1, dtype=bool)
    466 
--> 467     return where(mask, zeros(1, m.dtype), m)
    468 
    469 

MemoryError: 
`

**Comment by Csinclair0** [comment]
Hey, thanks for filing and apologies it has taken so long for me to respond. Rather odd the point of failure is the triangular upper matrix function. From what I've found, it looks like a common numpy issue that could potentially be solved by using a sparse implementation from scipy.

**Comment by Csinclair0** [comment]
Hey, I pushed an update moving it to scipy sparse matrices. You've probably moved on by now, but let me know if you try it again.
